language: node_js
node_js:
  - "6"
  - "5"
  - "5.0"
  - "4"
  - "0.12"
  - "iojs-v1"
  - "iojs-v2"
  - "iojs-v3"
script: "npm run-script test-travis"
after_script: "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"